name: Android

on:
  push:
    branches:
      - master
      - fix-ci
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'
      - 'android/**'
      - 'MMKV/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: printenv

      - name: Build Android apk (release)
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125
        run: |
          npm ci --legacy-peer-deps
          npm run build
          cd example
          npm ci --legacy-peer-deps
          cd android
          ./gradlew assembleRelease
